# Generated by Django 3.0.8 on 2020-10-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
